// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/mlsolid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MlsolidService_Experiments_FullMethodName = "/proto.MlsolidService/Experiments"
)

// MlsolidServiceClient is the client API for MlsolidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MlsolidServiceClient interface {
	Experiments(ctx context.Context, in *ExperimentsRequest, opts ...grpc.CallOption) (*ExperimentsResponse, error)
}

type mlsolidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMlsolidServiceClient(cc grpc.ClientConnInterface) MlsolidServiceClient {
	return &mlsolidServiceClient{cc}
}

func (c *mlsolidServiceClient) Experiments(ctx context.Context, in *ExperimentsRequest, opts ...grpc.CallOption) (*ExperimentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExperimentsResponse)
	err := c.cc.Invoke(ctx, MlsolidService_Experiments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlsolidServiceServer is the server API for MlsolidService service.
// All implementations must embed UnimplementedMlsolidServiceServer
// for forward compatibility.
type MlsolidServiceServer interface {
	Experiments(context.Context, *ExperimentsRequest) (*ExperimentsResponse, error)
	mustEmbedUnimplementedMlsolidServiceServer()
}

// UnimplementedMlsolidServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMlsolidServiceServer struct{}

func (UnimplementedMlsolidServiceServer) Experiments(context.Context, *ExperimentsRequest) (*ExperimentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Experiments not implemented")
}
func (UnimplementedMlsolidServiceServer) mustEmbedUnimplementedMlsolidServiceServer() {}
func (UnimplementedMlsolidServiceServer) testEmbeddedByValue()                        {}

// UnsafeMlsolidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MlsolidServiceServer will
// result in compilation errors.
type UnsafeMlsolidServiceServer interface {
	mustEmbedUnimplementedMlsolidServiceServer()
}

func RegisterMlsolidServiceServer(s grpc.ServiceRegistrar, srv MlsolidServiceServer) {
	// If the following call panics, it indicates UnimplementedMlsolidServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MlsolidService_ServiceDesc, srv)
}

func _MlsolidService_Experiments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExperimentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).Experiments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_Experiments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).Experiments(ctx, req.(*ExperimentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MlsolidService_ServiceDesc is the grpc.ServiceDesc for MlsolidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MlsolidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MlsolidService",
	HandlerType: (*MlsolidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Experiments",
			Handler:    _MlsolidService_Experiments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mlsolid.proto",
}
