// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/mlsolid.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperimentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentsRequest) Reset() {
	*x = ExperimentsRequest{}
	mi := &file_proto_mlsolid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentsRequest) ProtoMessage() {}

func (x *ExperimentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentsRequest.ProtoReflect.Descriptor instead.
func (*ExperimentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_proto_rawDescGZIP(), []int{0}
}

type ExperimentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpIds        []string               `protobuf:"bytes,1,rep,name=exp_ids,json=expIds,proto3" json:"exp_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentsResponse) Reset() {
	*x = ExperimentsResponse{}
	mi := &file_proto_mlsolid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentsResponse) ProtoMessage() {}

func (x *ExperimentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentsResponse.ProtoReflect.Descriptor instead.
func (*ExperimentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_proto_rawDescGZIP(), []int{1}
}

func (x *ExperimentsResponse) GetExpIds() []string {
	if x != nil {
		return x.ExpIds
	}
	return nil
}

var File_proto_mlsolid_proto protoreflect.FileDescriptor

const file_proto_mlsolid_proto_rawDesc = "" +
	"\n" +
	"\x13proto/mlsolid.proto\x12\x05proto\"\x14\n" +
	"\x12ExperimentsRequest\".\n" +
	"\x13ExperimentsResponse\x12\x17\n" +
	"\aexp_ids\x18\x01 \x03(\tR\x06expIds2V\n" +
	"\x0eMlsolidService\x12D\n" +
	"\vExperiments\x12\x19.proto.ExperimentsRequest\x1a\x1a.proto.ExperimentsResponseB Z\x1egithub.com/pvavrina/goml/protob\x06proto3"

var (
	file_proto_mlsolid_proto_rawDescOnce sync.Once
	file_proto_mlsolid_proto_rawDescData []byte
)

func file_proto_mlsolid_proto_rawDescGZIP() []byte {
	file_proto_mlsolid_proto_rawDescOnce.Do(func() {
		file_proto_mlsolid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mlsolid_proto_rawDesc), len(file_proto_mlsolid_proto_rawDesc)))
	})
	return file_proto_mlsolid_proto_rawDescData
}

var file_proto_mlsolid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mlsolid_proto_goTypes = []any{
	(*ExperimentsRequest)(nil),  // 0: proto.ExperimentsRequest
	(*ExperimentsResponse)(nil), // 1: proto.ExperimentsResponse
}
var file_proto_mlsolid_proto_depIdxs = []int32{
	0, // 0: proto.MlsolidService.Experiments:input_type -> proto.ExperimentsRequest
	1, // 1: proto.MlsolidService.Experiments:output_type -> proto.ExperimentsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mlsolid_proto_init() }
func file_proto_mlsolid_proto_init() {
	if File_proto_mlsolid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mlsolid_proto_rawDesc), len(file_proto_mlsolid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mlsolid_proto_goTypes,
		DependencyIndexes: file_proto_mlsolid_proto_depIdxs,
		MessageInfos:      file_proto_mlsolid_proto_msgTypes,
	}.Build()
	File_proto_mlsolid_proto = out.File
	file_proto_mlsolid_proto_goTypes = nil
	file_proto_mlsolid_proto_depIdxs = nil
}
